<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class CommuneSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("
            INSERT INTO `communes` (`id`, `nom`, `non`, `arrondissement`, `created_at`, `updated_at`) VALUES
            (1, 'Dessalines', 'Desalin', 2, NULL, NULL),
            (2, 'Desdunes', 'Dedin', 2, NULL, NULL),
            (3, 'Grande-Saline', ' Grann Salin', 2, NULL, NULL),
            (4, 'Petite Rivière de l\'Artibonite', 'Ti Rivyè Latibonit', 2, NULL, NULL),
            (5, 'GonaÃ¯ves', 'Gonayiv', 3, NULL, NULL),
            (6, 'Ennery', 'Eneri', 3, NULL, NULL),
            (7, 'L\'Estère', ' Lestè', 3, NULL, NULL),
            (8, 'Gros-Morne', 'Gwo Mòn', 4, NULL, NULL),
            (9, 'Anse-Rouge', 'Ans Wouj', 4, NULL, NULL),
            (10, 'Terre-Neuve', 'Tènèv', 4, NULL, NULL),
            (11, 'Marmelade', 'Manmlad', 5, NULL, NULL),
            (12, 'Saint-Michel-de-l\'Atalaye', 'Sen Michèl Latalay', 5, NULL, NULL),
            (13, 'Saint-Marc', 'Sen Mak', 1, NULL, NULL),
            (14, 'La Chapelle', 'Lachapèl', 1, NULL, NULL),
            (15, 'Liancourt', 'Lyankou', 1, NULL, NULL),
            (16, 'Verrettes', 'Vèrèt', 1, NULL, NULL),
            (17, 'Cerca-la-Source', 'Sèka Lasous', 6, NULL, NULL),
            (18, 'Thomassique', '	Tomasik', 6, NULL, NULL),
            (19, 'Hinche', 'Ench', 7, NULL, NULL),
            (20, 'Cerca-Carvajal', 'Sèka Kavajal', 7, NULL, NULL),
            (21, 'MaÃ¯ssade', 'Mayisad', 7, NULL, NULL),
            (22, 'Thomonde', ' Tomonn', 7, NULL, NULL),
            (23, 'Lascahobas', 'Laskawobas', 8, NULL, NULL),
            (24, 'Baptiste', 'Batis', 8, NULL, NULL),
            (25, 'Belladère', 'Beladè', 8, NULL, NULL),
            (26, 'Savanette', 'Savanèt', 8, NULL, NULL),
            (27, 'Mirebalais', 'Mibalè', 9, NULL, NULL),
            (28, 'Boucan-Carré', 'Boukan Kare', 9, NULL, NULL),
            (29, 'Saut-d\'Eau', 'Sodo', 9, NULL, NULL),
            (30, 'Anse-d\'Hainault', 'Ansdeno', 10, NULL, NULL),
            (31, 'Dame-Marie', 'Dam Mari', 10, NULL, NULL),
            (32, 'Les Irois', 'Lèziwa', 10, NULL, NULL),
            (33, 'Beaumont', 'Bomon', 11, NULL, NULL),
            (34, 'Corail', 'Koray', 11, NULL, NULL),
            (35, 'Pestel', 'Pestèl', 11, NULL, NULL),
            (36, 'Roseaux', 'Roze', 11, NULL, NULL),
            (37, 'Jérémie', 'Jeremi', 12, NULL, NULL),
            (38, 'Abricots', 'Abriko', 12, NULL, NULL),
            (39, 'Bonbon', 'Bonbon', 12, NULL, NULL),
            (40, 'Chambellan', 'Chanbèlan', 12, NULL, NULL),
            (41, 'Marfranc', 'Mafran', 12, NULL, NULL),
            (42, 'Moron', 'Moron', 12, NULL, NULL),
            (43, 'Anse-à-Veau', 'Ansavo', 13, NULL, NULL),
            (44, 'Arnaud', 'Lano', 13, NULL, NULL),
            (45, 'L\'Asile', 'Lazil', 13, NULL, NULL),
            (46, 'Petit-Trou-de-Nippes', 'Ti Twou de Nip', 13, NULL, NULL),
            (47, 'Plaisance-du-Sud', 'plezans disid', 13, NULL, NULL),
            (48, 'Baradères', 'Baradè', 14, NULL, NULL),
            (49, 'Grand-Boucan', 'Gran Boukan', 14, NULL, NULL),
            (50, 'Miragoâne', 'Miragwàn', 15, NULL, NULL),
            (51, 'Fonds-des-Nègres', 'Fondènèg', 15, NULL, NULL),
            (52, 'Paillant', 'Peyan', 15, NULL, NULL),
            (53, 'Petite-Rivière-de-Nippes', 'Ti Rivyè de Nip', 15, NULL, NULL),
            (54, 'Acul-du-Nord', 'Lakil dinò', 16, NULL, NULL),
            (55, 'Milot', 'Milo', 16, NULL, NULL),
            (56, 'Plaine-du-Nord', 'Plèn dinò', 16, NULL, NULL),
            (57, 'Borgne', 'Bòny', 17, NULL, NULL),
            (58, 'Port-Margot', 'Pò Mago', 17, NULL, NULL),
            (59, 'Cap-HaÃ¯tien', 'Kap Ayisyen', 18, NULL, NULL),
            (60, 'Limonade', 'Limonad', 18, NULL, NULL),
            (61, 'Quartier-Morin', 'Katye Moren', 18, NULL, NULL),
            (62, 'Grande-Rivière-du-Nord', 'Grann Rivyè dinò', 19, NULL, NULL),
            (63, 'Bahon', 'Bawon', 19, NULL, NULL),
            (64, 'Limbé', 'Lenbe', 20, NULL, NULL),
            (65, 'Bas-Limbé', 'Ba Lenbe', 20, NULL, NULL),
            (66, 'Plaisance', 'Plezans', 21, NULL, NULL),
            (67, 'Pilate', 'Pilat', 21, NULL, NULL),
            (68, 'Saint-Raphaël', 'Sen Rafayèl', 22, NULL, NULL),
            (69, 'Dondon', 'Dondon', 22, NULL, NULL),
            (70, 'La Victoire', 'Lavitwa', 22, NULL, NULL),
            (71, 'Pignon', 'Piyon', 22, NULL, NULL),
            (72, 'Ranquitte', 'Rankit', 22, NULL, NULL),
            (73, 'Fort-Liberté', 'Fòlibète', 23, NULL, NULL),
            (74, 'Perches', 'Pèch', 23, NULL, NULL),
            (75, 'Ferrier', 'Ferye', 23, NULL, NULL),
            (76, 'Ouanaminthe', 'Wanament', 24, NULL, NULL),
            (77, 'Capotille', 'Kapotiy', 24, NULL, NULL),
            (78, 'Mont-Organisé', 'Montòganize', 24, NULL, NULL),
            (79, 'Trou-du-Nord', 'Twou dinò', 25, NULL, NULL),
            (80, 'Caracol', 'Karakòl', 25, NULL, NULL),
            (81, 'Sainte-Suzanne', 'Sent Sizàn', 25, NULL, NULL),
            (82, 'Terrier-Rouge', 'Tèrye Wouj', 25, NULL, NULL),
            (83, 'Vallières', 'Valyè', 26, NULL, NULL),
            (84, 'Carice', 'Karis', 26, NULL, NULL),
            (85, 'Mombin-Crochu', 'Monben Kwochi', 26, NULL, NULL),
            (86, 'Môle-Saint-Nicolas', 'Mòl Sen Nikola', 27, NULL, NULL),
            (87, 'Baie-de-Henne', 'Bè de Hèn', 27, NULL, NULL),
            (88, 'Bombardopolis', 'Bonbadopolis', 27, NULL, NULL),
            (89, 'Jean-Rabel', 'Jan Rabèl', 27, NULL, NULL),
            (90, 'Port-de-Paix', 'Pòdpè', 28, NULL, NULL),
            (91, 'Bassin-Bleu', 'Basen Ble', 28, NULL, NULL),
            (92, 'Chansolme', 'Chansòl', 28, NULL, NULL),
            (93, 'La Pointe', 'Lapwent', 28, NULL, NULL),
            (94, 'La Tortue', 'Latòti', 28, NULL, NULL),
            (95, 'Saint-Louis-du-Nord', 'Sen Lwi dinò', 29, NULL, NULL),
            (96, 'Anse-à-Foleur', 'Ansafolè', 29, NULL, NULL),
            (97, 'Arcahaie', 'Lakayè', 30, NULL, NULL),
            (98, 'Cabaret', 'Kabarè', 30, NULL, NULL),
            (99, 'Croix-des-Bouquets', 'Kwadèbouke', 31, NULL, NULL),
            (100, 'Cornillon', 'Kòniyon', 31, NULL, NULL),
            (101, 'Fonds-Verrettes', 'Fonvèrèt', 31, NULL, NULL),
            (102, 'Ganthier', 'Gantye', 31, NULL, NULL),
            (103, 'Thomazeau', 'Tomazo', 31, NULL, NULL),
            (104, 'Anse-à-Galets', 'Ansagalèt', 32, NULL, NULL),
            (105, 'Pointe-à-Raquette', 'Pwentarakèt', 32, NULL, NULL),
            (106, 'Léogâne', 'Leyogàn', 33, NULL, NULL),
            (107, 'Grand-Goâve', 'Grangwav', 33, NULL, NULL),
            (108, 'Petit-Goâve', 'Tigwav', 33, NULL, NULL),
            (109, 'Port-au-Prince', 'Pòtoprens', 34, NULL, NULL),
            (110, 'Carrefour', 'Kafou', 34, NULL, NULL),
            (111, 'Cité Soleil', 'Site Solèy', 34, NULL, NULL),
            (112, 'Delmas', 'Dèlma', 34, NULL, NULL),
            (113, 'Gressier', 'Gresye', 34, NULL, NULL),
            (114, 'Kenscoff', 'Kenskòf', 34, NULL, NULL),
            (115, 'Pétion-Ville', 'Petyonvil', 34, NULL, NULL),
            (116, 'Tabarre', 'Taba', 34, NULL, NULL),
            (117, 'Bainet', 'Benè', 35, NULL, NULL),
            (118, 'Côtes-de-Fer', 'Kòt Defè', 35, NULL, NULL),
            (119, 'Belle-Anse', 'Bèlans', 36, NULL, NULL),
            (120, 'Anse-à-Pitres', 'Ansapit', 36, NULL, NULL),
            (121, 'Grand-Gosier', 'Gran Gozye', 36, NULL, NULL),
            (122, 'Thiotte', 'Tyòt', 36, NULL, NULL),
            (123, 'Jacmel', 'Jakmèl', 37, NULL, NULL),
            (124, 'Cayes-Jacmel', 'Kay Jakmèl', 37, NULL, NULL),
            (125, 'La Vallée', 'Lavale', 37, NULL, NULL),
            (126, 'Marigot', 'Marigo', 37, NULL, NULL),
            (127, 'Aquin', 'Aken', 38, NULL, NULL),
            (128, 'Cavaillon', 'Kavayon', 38, NULL, NULL),
            (129, 'Saint-Louis-du-Sud', 'Sen Lwi disid', 38, NULL, NULL),
            (130, 'Les Cayes', 'Okay', 39, NULL, NULL),
            (131, 'Camp-Perrin', 'Kanperen', 39, NULL, NULL),
            (132, 'Chantal', 'Chantal', 39, NULL, NULL),
            (133, 'Île-à-Vache', 'Lilavach', 39, NULL, NULL),
            (134, 'Maniche', 'Manich', 39, NULL, NULL),
            (135, 'Torbeck', 'Tòbèk', 39, NULL, NULL),
            (136, 'Chardonnières', 'Chadonyè', 40, NULL, NULL),
            (137, 'Les Anglais', 'Zanglè (Lèzanglè)', 40, NULL, NULL),
            (138, 'Tiburon', 'Tibiwon', 40, NULL, NULL),
            (139, 'Côteaux', 'koto', 41, NULL, NULL),
            (140, 'Port-à-Piment', 'Pòtapiman', 41, NULL, NULL),
            (141, 'Roche-à-Bateaux', 'Wòchabato', 41, NULL, NULL),
            (142, 'Port-Salut', '	Pòsali', 42, NULL, NULL),
            (143, 'Arniquet', 'Anikè', 42, NULL, NULL),
            (144, 'Saint-Jean-du-Sud', 'Sen Jan Disid', 42, NULL, NULL),
            (145, 'Mirebalais', 'Mibalè', 9, NULL, NULL)
        ");
    }
}
